---
- name: Create custom nginx html directory
  file:
    path: /usr/share/nginx/html-custom
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Deploy custom index page
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
    owner: root
    group: root
    mode: '0644'