---
- name: Create drawio application directory
  file:
    path: /opt/docker-apps/drawio
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Deploy Draw.io docker-compose configuration
  template:
    src: docker-compose.yml.j2
    dest: /opt/docker-apps/drawio/docker-compose.yml
    owner: root
    group: root
    mode: '0644'
  notify: restart drawio

- name: Pull Draw.io Docker image
  command: docker pull jgraph/drawio:latest
  register: docker_pull_result
  changed_when: "'Downloaded newer image' in docker_pull_result.stderr or 'Pull complete' in docker_pull_result.stderr"

- name: Start Draw.io container using docker-compose
  command: docker-compose up -d
  args:
    chdir: /opt/docker-apps/drawio
  register: docker_compose_result
  changed_when: "'Starting' in docker_compose_result.stderr or 'Created' in docker_compose_result.stderr"

- name: Create systemd service for Draw.io
  template:
    src: drawio.service.j2
    dest: /etc/systemd/system/drawio.service
    owner: root
    group: root
    mode: '0644'
  notify: reload systemd

- name: Enable and start Draw.io service
  systemd:
    name: drawio
    enabled: yes
    state: started
    daemon_reload: yes

- name: Wait for Draw.io to be ready
  wait_for:
    port: "{{ drawio_port }}"
    host: "127.0.0.1"
    delay: 10
    timeout: 60

- name: Verify Draw.io is running
  uri:
    url: "http://127.0.0.1:{{ drawio_port }}"
    method: GET
    status_code: 200
  register: drawio_check
  retries: 3
  delay: 10